name: Feature request
description: Suggest an idea for this project
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: input
    id: title
    attributes:
      label: What would you like to see?
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the feature you'd like
      placeholder: Tell us what you want to see and why you think it would be useful
    validations:
      required: true
