on: pull_request

jobs:
  pr-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        env:
          GRADLE_HOME: ${{ github.workspace }}/.gradle
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
          cache-dependency-path: |
            .gradle

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            .gradle/caches
            .gradle/wrapper

      - name: Validate compilation
        run: ./gradlew build --parallel
        env:
          GRADLE_HOME: ${{ github.workspace }}/.gradle

      - run: ./gradlew :plugin:verifyPluginCompatibility --parallel
        env:
          GRADLE_HOME: ${{ github.workspace }}/.gradle
